logging:
  file:
    name: ${user.dir}/log/test.log
    max-history: '7'
    max-size: 10MB
  level:
    gocha:
      jjamppong:
        controller: debug
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
      springframework:
        security: DEBUG
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    password: '0000'
    username: root
    url: jdbc:mariadb://localhost:3306/Jjamppong

  jpa:
    properties:
      hibernate:
        highlight_sql: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update

#  profiles:
#    include: db

