logging:
  file:
    name: ${user.dir}/log/test.log
    max-history: '7'
    max-size: 10MB
  level:
    gocha:
      jjamppong:
        controller: debug
    org:
      hibernate:
        orm:
          jdbc:
#            bind: trace
            bind: INFO
      springframework:
#        security: DEBUG
        security: INFO
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver


  jpa:
    properties:
      hibernate:
#        highlight_sql: 'true'
#        format_sql: 'true'
#        show_sql: 'true'
    hibernate:
      ddl-auto: update

#  profiles:
#    include: localdb

  profiles:
    include: rdsdb

#  profiles:
#    include: dockerdb



